import * as Phaser from "phaser";
import type { UnitRole } from "@shared/events";

// Four-keyblader system. Each archetype has a primitive silhouette
// used only when no sprite-sheet override is loaded. The procedural
// look is intentionally simple — the real visual layer is whatever
// the user drops into `assets/sprites/kh/keybladerN_sheet.png`.
export const UNIT_ROLES: UnitRole[] = [
  "keyblader1",
  "keyblader2",
  "keyblader3",
  "keyblader4",
];

// User override path (gitignored — drop your own sprites here).
export const SPRITE_URL = (role: UnitRole) => `/sprites/kh/${role}.png`;
export const TEXTURE_KEY = (role: UnitRole) => `kh-unit-${role}`;

// Shipped default art generated by scripts/generate-pixel-sprites.ts.
export const SPRITE_DEFAULT_URL = (role: UnitRole) =>
  `/sprites/kh-default/${role}.png`;
export const TEXTURE_DEFAULT_KEY = (role: UnitRole) => `kh-default-${role}`;

const SKIN = 0xf5cba0;

/**
 * Primitive chibi silhouette used as a last-resort fallback when no
 * sprite is loaded. Four distinguishable archetypes — keyblader1
 * (Vaelen, twilight purple), keyblader2 (Selene, dream pink),
 * keyblader3 (Ryder, forge orange), keyblader4 (Lyris, tide cyan).
 */
export function drawKHUnit(
  scene: Phaser.Scene,
  role: UnitRole
): Phaser.GameObjects.GameObject[] {
  switch (role) {
    case "keyblader2": return drawKeyblader2(scene);
    case "keyblader3": return drawKeyblader3(scene);
    case "keyblader4": return drawKeyblader4(scene);
    default: return drawKeyblader1(scene);
  }
}

// Masculine keyblader — dark navy/purple coat, spiky dark hair.
function drawKeyblader1(scene: Phaser.Scene): Phaser.GameObjects.GameObject[] {
  const objs: Phaser.GameObjects.GameObject[] = [];
  // Body — dark coat
  objs.push(
    scene.add.rectangle(0, 12, 18, 16, 0x3a2870).setStrokeStyle(1.5, 0x000000, 0.7)
  );
  // Gold trim down center
  objs.push(scene.add.rectangle(0, 12, 1.4, 14, 0xd8a830));
  // Black boots
  objs.push(scene.add.rectangle(-5, 21, 6, 4, 0x1a1a1a).setStrokeStyle(1, 0x000000, 0.7));
  objs.push(scene.add.rectangle(5, 21, 6, 4, 0x1a1a1a).setStrokeStyle(1, 0x000000, 0.7));
  // Head
  objs.push(scene.add.circle(0, -4, 11, SKIN).setStrokeStyle(1, 0x3a2010, 0.8));
  // Spiky dark hair
  const hair = scene.add.graphics();
  hair.fillStyle(0x1a1430, 1);
  hair.lineStyle(1, 0x000000, 0.85);
  const spikes: [number, number, number, number, number, number][] = [
    [-13, -6, -7, -22, -2, -7],
    [-8, -6, -2, -24, 4, -7],
    [-2, -7, 4, -22, 8, -7],
    [4, -7, 12, -19, 12, -7],
  ];
  spikes.forEach(([x1, y1, x2, y2, x3, y3]) => {
    hair.fillTriangle(x1, y1, x2, y2, x3, y3);
    hair.strokeTriangle(x1, y1, x2, y2, x3, y3);
  });
  hair.fillEllipse(0, -8, 18, 6);
  objs.push(hair);
  // Blue eyes
  objs.push(scene.add.ellipse(-3.5, -3, 2.6, 3.4, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.ellipse(3.5, -3, 2.6, 3.4, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.circle(-3.5, -3, 1.1, 0x2c5e8a));
  objs.push(scene.add.circle(3.5, -3, 1.1, 0x2c5e8a));
  return objs;
}

// Feminine keyblader — pale lavender/pink robes, long pink hair.
function drawKeyblader2(scene: Phaser.Scene): Phaser.GameObjects.GameObject[] {
  const objs: Phaser.GameObjects.GameObject[] = [];
  // Body — flowing robes
  objs.push(
    scene.add.rectangle(0, 12, 16, 16, 0xf0c0d8).setStrokeStyle(1.5, 0x6a4060, 0.7)
  );
  // Silver belt
  objs.push(scene.add.rectangle(0, 14, 16, 1.4, 0xb8b8c8));
  // Lavender skirt visible at bottom
  objs.push(scene.add.rectangle(0, 18, 18, 6, 0xc8a0d0).setStrokeStyle(1, 0x6a4060, 0.7));
  // Sandals
  objs.push(scene.add.rectangle(-5, 22, 5, 2.5, 0xb8b8c8));
  objs.push(scene.add.rectangle(5, 22, 5, 2.5, 0xb8b8c8));
  // Head
  objs.push(scene.add.circle(0, -4, 11, SKIN).setStrokeStyle(1, 0x3a2010, 0.7));
  // Long pink hair past shoulders
  const hair = scene.add.graphics();
  hair.fillStyle(0xf0c0d8, 1);
  hair.lineStyle(1, 0xa86878, 0.85);
  hair.fillEllipse(0, -12, 24, 12);
  hair.fillEllipse(-10, 0, 6, 18);
  hair.fillEllipse(10, 0, 6, 18);
  // Soft forehead bangs
  hair.fillTriangle(-7, -7, 4, -5, -2, 1);
  hair.fillTriangle(2, -7, 9, -3, 5, 1);
  hair.strokeEllipse(0, -12, 24, 12);
  objs.push(hair);
  // Amber eyes
  objs.push(scene.add.ellipse(-3.5, -3, 2.4, 3, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.ellipse(3.5, -3, 2.4, 3, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.circle(-3.5, -3, 1, 0xa07020));
  objs.push(scene.add.circle(3.5, -3, 1, 0xa07020));
  return objs;
}

// Masculine keyblader — crimson cloak over dark tunic, copper hair.
function drawKeyblader3(scene: Phaser.Scene): Phaser.GameObjects.GameObject[] {
  const objs: Phaser.GameObjects.GameObject[] = [];
  // Body — dark tunic
  objs.push(
    scene.add.rectangle(0, 12, 18, 16, 0x586068).setStrokeStyle(1.5, 0x000000, 0.7)
  );
  // Crimson cloak draped over shoulders
  objs.push(scene.add.rectangle(-8, 11, 4, 18, 0x883028).setStrokeStyle(1, 0x000000, 0.7));
  objs.push(scene.add.rectangle(8, 11, 4, 18, 0x883028).setStrokeStyle(1, 0x000000, 0.7));
  // Brass belt buckle
  objs.push(scene.add.rectangle(0, 16, 4, 2, 0xc89040));
  // Iron-toed boots
  objs.push(scene.add.rectangle(-5, 21, 6, 4, 0x2a2a2a).setStrokeStyle(1, 0x000000, 0.7));
  objs.push(scene.add.rectangle(5, 21, 6, 4, 0x2a2a2a).setStrokeStyle(1, 0x000000, 0.7));
  // Head
  objs.push(scene.add.circle(0, -4, 11, SKIN).setStrokeStyle(1, 0x3a2010, 0.8));
  // Tousled copper hair
  const hair = scene.add.graphics();
  hair.fillStyle(0xa85838, 1);
  hair.lineStyle(1, 0x4a2818, 0.85);
  hair.fillEllipse(0, -10, 20, 8);
  hair.fillTriangle(-10, -8, -4, -18, 0, -8);
  hair.fillTriangle(-2, -8, 5, -18, 8, -8);
  hair.fillTriangle(4, -8, 10, -16, 12, -8);
  hair.strokeEllipse(0, -10, 20, 8);
  objs.push(hair);
  // Amber eyes
  objs.push(scene.add.ellipse(-3.5, -3, 2.6, 3.4, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.ellipse(3.5, -3, 2.6, 3.4, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.circle(-3.5, -3, 1.1, 0xa05818));
  objs.push(scene.add.circle(3.5, -3, 1.1, 0xa05818));
  return objs;
}

// Feminine keyblader — cyan tunic over white undershirt, teal hair.
function drawKeyblader4(scene: Phaser.Scene): Phaser.GameObjects.GameObject[] {
  const objs: Phaser.GameObjects.GameObject[] = [];
  // Body — cyan tunic
  objs.push(
    scene.add.rectangle(0, 12, 16, 16, 0x5cc8d8).setStrokeStyle(1.5, 0x2a4858, 0.7)
  );
  // Navy sash at waist
  objs.push(scene.add.rectangle(0, 14, 16, 1.6, 0x203848));
  // Teal trousers
  objs.push(scene.add.rectangle(0, 20, 14, 6, 0x2a7088).setStrokeStyle(1, 0x000000, 0.7));
  // White wrap-boots
  objs.push(scene.add.rectangle(-4, 23, 5, 2.5, 0xf8f8f0));
  objs.push(scene.add.rectangle(4, 23, 5, 2.5, 0xf8f8f0));
  // Silver pauldron on left shoulder
  objs.push(scene.add.circle(-8, 6, 2.4, 0xb0b8c0).setStrokeStyle(0.8, 0x000000, 0.7));
  // Head
  objs.push(scene.add.circle(0, -4, 11, SKIN).setStrokeStyle(1, 0x3a2010, 0.7));
  // Wavy teal hair, half-back
  const hair = scene.add.graphics();
  hair.fillStyle(0x5cc8d8, 1);
  hair.lineStyle(1, 0x2a7088, 0.85);
  hair.fillEllipse(0, -11, 22, 10);
  hair.fillEllipse(-9, 1, 5, 14);
  hair.fillEllipse(9, 1, 5, 14);
  hair.fillTriangle(-7, -7, 4, -5, -2, 1);
  hair.strokeEllipse(0, -11, 22, 10);
  objs.push(hair);
  // Silver clasp
  objs.push(scene.add.circle(-7, -10, 1.1, 0xb0b8c0));
  // Sea-green eyes
  objs.push(scene.add.ellipse(-3.5, -3, 2.4, 3, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.ellipse(3.5, -3, 2.4, 3, 0xffffff).setStrokeStyle(0.8, 0x000000, 1));
  objs.push(scene.add.circle(-3.5, -3, 1, 0x2a7088));
  objs.push(scene.add.circle(3.5, -3, 1, 0x2a7088));
  return objs;
}

// World landmarks — kept as primitive fallbacks for when pixel
// landmark images aren't loaded. Drawn at absolute (x, y).
export function drawKHBuilding(
  scene: Phaser.Scene,
  kind: "disney" | "hollow" | "traverse",
  x: number,
  y: number
): Phaser.GameObjects.GameObject[] {
  const objs: Phaser.GameObjects.GameObject[] = [];
  switch (kind) {
    case "disney": {
      const base = scene.add
        .rectangle(x, y, 50, 18, 0x0a1130, 0.95)
        .setStrokeStyle(1, 0x6cc6ff, 0.5);
      const wall = scene.add
        .rectangle(x, y - 18, 30, 28, 0xeef7ff)
        .setStrokeStyle(1, 0x6cc6ff, 0.7);
      const tower = scene.add
        .rectangle(x - 16, y - 32, 12, 30, 0x6cc6ff)
        .setStrokeStyle(1, 0xffffff, 0.7);
      const tower2 = scene.add
        .rectangle(x + 16, y - 32, 12, 30, 0x6cc6ff)
        .setStrokeStyle(1, 0xffffff, 0.7);
      const peakC = scene.add.triangle(x, y - 56, -18, 14, 18, 14, 0, -16, 0xffd86b);
      objs.push(base, wall, tower, tower2, peakC);
      break;
    }
    case "hollow": {
      const base = scene.add
        .rectangle(x, y, 42, 16, 0x05080d, 1)
        .setStrokeStyle(1, 0xffd86b, 0.4);
      const wall = scene.add
        .rectangle(x, y - 16, 28, 26, 0x1a1426)
        .setStrokeStyle(1, 0x9d6bff, 0.7);
      const tallSpire = scene.add
        .rectangle(x, y - 52, 7, 40, 0x1a1426)
        .setStrokeStyle(1, 0xffd86b, 0.7);
      const keyholeRing = scene.add
        .circle(x, y - 18, 4, 0x000000, 0)
        .setStrokeStyle(1.6, 0xffd86b, 1);
      const keyholeStem = scene.add.rectangle(x, y - 12, 2.5, 7, 0xffd86b);
      objs.push(base, wall, tallSpire, keyholeRing, keyholeStem);
      break;
    }
    case "traverse": {
      const base = scene.add
        .rectangle(x, y, 46, 14, 0x1a0f08, 1)
        .setStrokeStyle(1, 0xffd86b, 0.4);
      const left = scene.add
        .rectangle(x - 13, y - 16, 18, 24, 0x6b4423)
        .setStrokeStyle(1, 0xffd86b, 0.6);
      const right = scene.add
        .rectangle(x + 11, y - 14, 18, 20, 0x8a5530)
        .setStrokeStyle(1, 0xffd86b, 0.5);
      const roofL = scene.add.triangle(x - 13, y - 32, -11, 8, 11, 8, 0, -8, 0xff7a3c);
      const roofR = scene.add.triangle(x + 11, y - 26, -11, 6, 11, 6, 0, -8, 0xff7a3c);
      const lamp = scene.add.circle(x + 21, y - 16, 3, 0xffd86b);
      objs.push(base, left, right, roofL, roofR, lamp);
      break;
    }
  }
  return objs;
}
